baseURL = "https://rocketup.pages.dev/"
languageCode = 'en-us'
title = 'rocketup - blog on (almost) anything'
theme = "paper"
sectionPagesMenu = 'main'
math = true

[params]
math = true
rss = true                                # show rss icon
github = 'gi-dellav'
mastodon = 'gi-dellav'
bluesky = 'gi-dellav'

#[params.giscus]
#  repo = 'gi-dellav/rocketup'                 # see https://giscus.app for more details
#  repoId = 'R_kgDOPkbq6Q'
#  category = 'Q&A'
#  categoryId = 'DIC_kwDOPkbq6c4CxIll'
#  mapping = 'pathname'
#  theme = 'noborder_dark'
#  lang = 'en-EN'
